"""autogenerated by genpy from my_simulation/temp_map.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class temp_map(genpy.Message):
  _md5sum = "30919d1f5a6fe62bba54235b749bff7c"
  _type = "my_simulation/temp_map"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool use_temp_map
string map_name
geometry_msgs/Point temp_origin
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['use_temp_map','map_name','temp_origin']
  _slot_types = ['bool','string','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       use_temp_map,map_name,temp_origin

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(temp_map, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.use_temp_map is None:
        self.use_temp_map = False
      if self.map_name is None:
        self.map_name = ''
      if self.temp_origin is None:
        self.temp_origin = geometry_msgs.msg.Point()
    else:
      self.use_temp_map = False
      self.map_name = ''
      self.temp_origin = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.use_temp_map))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.temp_origin.x, _x.temp_origin.y, _x.temp_origin.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.temp_origin is None:
        self.temp_origin = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 1
      (self.use_temp_map,) = _struct_B.unpack(str[start:end])
      self.use_temp_map = bool(self.use_temp_map)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8')
      else:
        self.map_name = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.temp_origin.x, _x.temp_origin.y, _x.temp_origin.z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.use_temp_map))
      _x = self.map_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.temp_origin.x, _x.temp_origin.y, _x.temp_origin.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.temp_origin is None:
        self.temp_origin = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 1
      (self.use_temp_map,) = _struct_B.unpack(str[start:end])
      self.use_temp_map = bool(self.use_temp_map)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_name = str[start:end].decode('utf-8')
      else:
        self.map_name = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.temp_origin.x, _x.temp_origin.y, _x.temp_origin.z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_3d = struct.Struct("<3d")
